# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'infer_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InferWindow(object):
    def setupUi(self, InferWindow):
        InferWindow.setObjectName("InferWindow")
        InferWindow.resize(734, 550)
        self.WT2 = QtWidgets.QWidget(InferWindow)
        self.WT2.setObjectName("WT2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.WT2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_top = QtWidgets.QWidget(self.WT2)
        self.widget_top.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_top.setObjectName("widget_top")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_top)
        self.horizontalLayout_2.setContentsMargins(9, 0, -1, 0)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_tl = QtWidgets.QWidget(self.widget_top)
        self.widget_tl.setObjectName("widget_tl")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_tl)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_tlt = QtWidgets.QWidget(self.widget_tl)
        self.widget_tlt.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.widget_tlt.setObjectName("widget_tlt")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_tlt)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.widget_tlt)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.verticalLayout_2.addWidget(self.widget_tlt)
        self.widget_tlb = QtWidgets.QWidget(self.widget_tl)
        self.widget_tlb.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.widget_tlb.setObjectName("widget_tlb")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_tlb)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")

        self.label_2 = QtWidgets.QLabel(self.widget_tlb)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)

        self.label_3 = QtWidgets.QLabel(self.widget_tlb)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.widget_tlb)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.horizontalLayout_4.setStretch(0, 4)
        self.horizontalLayout_4.setStretch(1, 1)
        self.horizontalLayout_4.setStretch(2, 10)
        self.verticalLayout_2.addWidget(self.widget_tlb)
        self.verticalLayout_2.setStretch(0, 8)
        self.verticalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.addWidget(self.widget_tl)

        self.widget_tr = QtWidgets.QWidget(self.widget_top)
        self.widget_tr.setObjectName("widget_tr")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_tr) # 改为垂直布局
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        # self.label = QtWidgets.QLabel(self.widget_tr)
        # self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        # self.label.setStyleSheet("background-color: rgb(255, 170, 127);")
        # self.label.setObjectName("label")
        # self.horizontalLayout_3.addWidget(self.label)
        # 添加解释标题
        self.label_explain_title = QtWidgets.QLabel(self.widget_tr)
        self.label_explain_title.setText("解释结果：")
        self.verticalLayout_3.addWidget(self.label_explain_title)

        # 将原来的QLabel改为QTextEdit
        self.textEdit = QtWidgets.QTextEdit(self.widget_tr)
        self.textEdit.setObjectName("textEdit")
        self.textEdit.setStyleSheet("""
                    QTextEdit {
                        background-color: rgb(255, 255, 255);
                        border: 2px solid #cccccc;
                        padding: 8px;
                        font-size: 12pt;
                    }
                """)
        self.textEdit.setReadOnly(True)
        self.textEdit.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)  # 自动换行
        self.verticalLayout_3.addWidget(self.textEdit)
        self.horizontalLayout_2.addWidget(self.widget_tr)


        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout.addWidget(self.widget_top)
        self.widget_bottom = QtWidgets.QWidget(self.WT2)
        self.widget_bottom.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_bottom.setObjectName("widget_bottom")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_bottom)
        self.horizontalLayout.setContentsMargins(9, 0, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.widget_bottom)
        self.pushButton.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setFixedHeight(50)
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_bottom)
        self.pushButton_2.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setFixedHeight(50)
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_bottom)
        self.pushButton_3.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.setFixedHeight(50)
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_bottom)
        self.pushButton_4.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.setFixedHeight(50)
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.verticalLayout.addWidget(self.widget_bottom)
        self.verticalLayout.setStretch(0, 6)
        self.verticalLayout.setStretch(1, 1)
        InferWindow.setCentralWidget(self.WT2)

        self.retranslateUi(InferWindow)
        QtCore.QMetaObject.connectSlotsByName(InferWindow)

    def retranslateUi(self, InferWindow):
        _translate = QtCore.QCoreApplication.translate
        InferWindow.setWindowTitle(_translate("InferWindow", "MainWindow"))
        self.label_5.setText(_translate("InferWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt;\">等待上传图片</span></p></body></html>"))
        self.label_2.setText(_translate("InferWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">预测年龄：</span></p></body></html>"))
        self.label_3.setText(_translate("InferWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">0</span></p></body></html>"))
        # self.label_4.setText(_translate("InferWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">月</span></p></body></html>"))
        # self.label.setAlignment(QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)  # 设置左上角对齐
        # self.label.setText(_translate("InferWindow", "解释："))
        # 修改标签文本
        self.label_explain_title.setText(_translate("InferWindow", "养护建议："))
        self.pushButton.setText(_translate("InferWindow", "读取图片"))
        self.pushButton_2.setText(_translate("InferWindow", "开始推理"))
        self.pushButton_3.setText(_translate("InferWindow", "结果解释"))
        self.pushButton_4.setText(_translate("InferWindow", "返回首页"))
