# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nav_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NavWindow(object):
    def setupUi(self, NavWindow):
        NavWindow.setObjectName("NavWindow")
        NavWindow.resize(671, 468)
        self.WT = QtWidgets.QWidget(NavWindow)
        self.WT.setObjectName("WT")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.WT)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_top = QtWidgets.QWidget(self.WT)
        self.widget_top.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.widget_top.setObjectName("widget_top")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_top)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.title = QtWidgets.QLabel(self.widget_top)
        self.title.setObjectName("title")
        self.verticalLayout_2.addWidget(self.title)
        self.verticalLayout.addWidget(self.widget_top)
        self.widget_bottom = QtWidgets.QWidget(self.WT)
        self.widget_bottom.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_bottom.setObjectName("widget_bottom")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_bottom)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_bl = QtWidgets.QWidget(self.widget_bottom)
        self.widget_bl.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.widget_bl.setObjectName("widget_bl")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_bl)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.widget_bl)
        # 按钮
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setFixedHeight(100)
        self.pushButton.setStyleSheet("font-size: 16pt;")
        self.verticalLayout_3.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_bl)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setFixedHeight(100)
        self.pushButton_2.setStyleSheet("font-size: 16pt;")
        self.verticalLayout_3.addWidget(self.pushButton_2)

        self.horizontalLayout.addWidget(self.widget_bl)
        self.widget_br = QtWidgets.QWidget(self.widget_bottom)
        self.widget_br.setObjectName("widget_br")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_br)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.widget_br)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("image: url(:/dog/show.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.horizontalLayout.addWidget(self.widget_br)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)
        self.verticalLayout.addWidget(self.widget_bottom)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 6)
        NavWindow.setCentralWidget(self.WT)

        # 在这里设置图片
        self.setImageToLabel()

        self.retranslateUi(NavWindow)
        QtCore.QMetaObject.connectSlotsByName(NavWindow)

    def setImageToLabel(self):
        pixmap = QtGui.QPixmap(":/dog/show.jpg")  # 请确保这条路径正确
        self.label.setPixmap(
            pixmap.scaled(self.label.size(), QtCore.Qt.KeepAspectRatioByExpanding, QtCore.Qt.SmoothTransformation))
        self.label.setScaledContents(True)  # 设置标签使内容缩放以填充标签

    def retranslateUi(self, NavWindow):
        _translate = QtCore.QCoreApplication.translate
        NavWindow.setWindowTitle(_translate("NavWindow", "MainWindow"))
        self.title.setText(_translate("NavWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600;\">卷毛比熊犬年龄识别系统</span></p></body></html>"))
        self.pushButton.setText(_translate("NavWindow", "图片识别"))
        self.pushButton_2.setText(_translate("NavWindow", "退出"))
import dog
import lsx
